// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryPatternTask.Data.Context;

#nullable disable

namespace RepositoryPatternTask.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326050734_testSeeder")]
    partial class testSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RepositoryPatternTask.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = "33333333-3333-3333-3333-333333333333",
                            Name = "Books"
                        },
                        new
                        {
                            Id = "44444444-4444-4444-4444-444444444444",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = "55555555-5555-5555-5555-555555555555",
                            Name = "Food"
                        });
                });

            modelBuilder.Entity("RepositoryPatternTask.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "11111111-0000-0000-0000-000000000001",
                            CategoryId = "11111111-1111-1111-1111-111111111111",
                            Name = "Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = "11111111-0000-0000-0000-000000000002",
                            CategoryId = "11111111-1111-1111-1111-111111111111",
                            Name = "Smartphone",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = "11111111-0000-0000-0000-000000000003",
                            CategoryId = "11111111-1111-1111-1111-111111111111",
                            Name = "Headphones",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = "11111111-0000-0000-0000-000000000004",
                            CategoryId = "11111111-1111-1111-1111-111111111111",
                            Name = "Tablet",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = "11111111-0000-0000-0000-000000000005",
                            CategoryId = "11111111-1111-1111-1111-111111111111",
                            Name = "Smart Watch",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = "22222222-0000-0000-0000-000000000001",
                            CategoryId = "22222222-2222-2222-2222-222222222222",
                            Name = "T-Shirt",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = "22222222-0000-0000-0000-000000000002",
                            CategoryId = "22222222-2222-2222-2222-222222222222",
                            Name = "Jeans",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = "22222222-0000-0000-0000-000000000003",
                            CategoryId = "22222222-2222-2222-2222-222222222222",
                            Name = "Jacket",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = "22222222-0000-0000-0000-000000000004",
                            CategoryId = "22222222-2222-2222-2222-222222222222",
                            Name = "Sneakers",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = "22222222-0000-0000-0000-000000000005",
                            CategoryId = "22222222-2222-2222-2222-222222222222",
                            Name = "Hat",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = "33333333-0000-0000-0000-000000000001",
                            CategoryId = "33333333-3333-3333-3333-333333333333",
                            Name = "Clean Code",
                            Price = 34.99m
                        },
                        new
                        {
                            Id = "33333333-0000-0000-0000-000000000002",
                            CategoryId = "33333333-3333-3333-3333-333333333333",
                            Name = "The Pragmatic Programmer",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = "33333333-0000-0000-0000-000000000003",
                            CategoryId = "33333333-3333-3333-3333-333333333333",
                            Name = "Design Patterns",
                            Price = 44.99m
                        },
                        new
                        {
                            Id = "33333333-0000-0000-0000-000000000004",
                            CategoryId = "33333333-3333-3333-3333-333333333333",
                            Name = "C# in Depth",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = "33333333-0000-0000-0000-000000000005",
                            CategoryId = "33333333-3333-3333-3333-333333333333",
                            Name = "ASP.NET Core",
                            Price = 37.99m
                        },
                        new
                        {
                            Id = "44444444-0000-0000-0000-000000000001",
                            CategoryId = "44444444-4444-4444-4444-444444444444",
                            Name = "Football",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = "44444444-0000-0000-0000-000000000002",
                            CategoryId = "44444444-4444-4444-4444-444444444444",
                            Name = "Tennis Racket",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = "44444444-0000-0000-0000-000000000003",
                            CategoryId = "44444444-4444-4444-4444-444444444444",
                            Name = "Yoga Mat",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = "44444444-0000-0000-0000-000000000004",
                            CategoryId = "44444444-4444-4444-4444-444444444444",
                            Name = "Running Shoes",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = "44444444-0000-0000-0000-000000000005",
                            CategoryId = "44444444-4444-4444-4444-444444444444",
                            Name = "Dumbbells",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = "55555555-0000-0000-0000-000000000001",
                            CategoryId = "55555555-5555-5555-5555-555555555555",
                            Name = "Protein Bar",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = "55555555-0000-0000-0000-000000000002",
                            CategoryId = "55555555-5555-5555-5555-555555555555",
                            Name = "Olive Oil",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = "55555555-0000-0000-0000-000000000003",
                            CategoryId = "55555555-5555-5555-5555-555555555555",
                            Name = "Green Tea",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = "55555555-0000-0000-0000-000000000004",
                            CategoryId = "55555555-5555-5555-5555-555555555555",
                            Name = "Almonds",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = "55555555-0000-0000-0000-000000000005",
                            CategoryId = "55555555-5555-5555-5555-555555555555",
                            Name = "Honey",
                            Price = 6.99m
                        });
                });

            modelBuilder.Entity("RepositoryPatternTask.Models.Product", b =>
                {
                    b.HasOne("RepositoryPatternTask.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RepositoryPatternTask.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
